includes = "-I" "src\include" "-I" "SDL\include" "-I" "SDL_TTF\include"
libs = "-L" "SDL\lib" "-L" "SDL_TTF\lib" "src\lib\**"
dlls = "-lSDL2main" "-lSDL2" "-lSDL2_ttf"


build:
	g++ "-g3" "-std=c++20" ${includes} ${libs} "test\Test.cpp" "-o" "test\Test.exe" ${dlls}
