includes = "-I" "Hazard-Engine\include" "-I" "SDL\include" "-I" "SDL_TTF\include"
libs = "-L" "SDL\lib" "-L" "SDL_TTF\lib"
dlls = "-lSDL2main" "-lSDL2" "-lSDL2_ttf"

outFileName = Main


build:
	g++ "-g3" "-std=c++20" ${includes} ${libs} "src\Main.cpp" "Hazard-Engine\lib\**" "-o" "out\${outFileName}.exe" ${dlls}
